### ISSUE TITLE
Automate Start Date

### ISSUE THREAD

**Issue by ZackAttack614** [prundstrom/curiosity-code#2]
Instead of manually updating the simulation start date in the `parameters/params.yaml` file, you can replace the line below with an automated system time grab.

https://github.com/lab-example-organization/curiosity-code/blob/88ffb77b19f610d021b64a0f703e5c1c59d6efd5/scripts/Source_Multiple_Runs.R#L236

Goes to...

```r
simStartDate = gsub('-', '', substring(Sys.Date(), 3))
```

**Comment by prundstrom** [comment]
changed! Thanks for the fix, you have indeed saved me much annoyance
